"""available_uses 0 to 5

Revision ID: 6ae1ae0d6eaf
Revises: 321d59a4049f
Create Date: 2024-12-18 18:02:55.109826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae1ae0d6eaf'
down_revision: Union[str, None] = '321d59a4049f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
